In [4]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv('/content/youtube_ad_revenue_dataset.csv')
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110771 entries, 0 to 110770
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   video_id              110771 non-null  object
 1   date                  110770 non-null  object
 2   views                 110770 non-null  float64
 3   likes                 105257 non-null  float64
 4   comments              105232 non-null  float64
 5   watch_time_minutes    105222 non-null  float64
 6   video_length_minutes  110770 non-null  float64
 7   subscribers           110770 non-null  float64
 8   category              110770 non-null  object
 9   device                110770 non-null  object
 10  country               110770 non-null  object
 11  ad_revenue_usd        110770 non-null  float64
dtypes: float64(7), object(5)
memory usage: 10.1+ MB
None

In [5]:
print(df.columns)

Index(['video_id', 'date', 'views', 'likes', 'comments', 'watch_time_minutes',
       'video_length_minutes', 'subscribers', 'category', 'device', 'country',
       'ad_revenue_usd'],
      dtype='object')

In [8]:
print(df.isnull().sum())

video_id                0
date                    1
views                   1
likes                   0
comments                0
watch_time_minutes      0
video_length_minutes    1
subscribers             1
category                1
device                  1
country                 1
ad_revenue_usd          1
dtype: int64

In [7]:
df['likes'] = df['likes'].fillna(df['likes'].median())
df['comments'] = df['comments'].fillna(df['comments'].median())
df['watch_time_minutes'] = df['watch_time_minutes'].fillna(df['watch_time_minutes'].median())

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error, r2_score

# Regression models
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor

In [10]:
X = df.drop("ad_revenue_usd", axis=1)
y = df["ad_revenue_usd"]

In [11]:
X

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country
0,vid_3092,2024-09-24 10:50:40.993199,9936.0,1221.0,320.0,26497.214184,2.862137,228086.0,Entertainment,TV,IN
1,vid_3459,2024-09-22 10:50:40.993199,10017.0,642.0,346.0,15209.747445,23.738069,736015.0,Gaming,Tablet,CA
2,vid_4784,2024-11-21 10:50:40.993199,10097.0,1979.0,187.0,57332.658498,26.200634,240534.0,Education,TV,CA
3,vid_4078,2025-01-28 10:50:40.993199,10034.0,1191.0,242.0,31334.517771,11.770340,434482.0,Entertainment,Mobile,UK
4,vid_3522,2025-04-28 10:50:40.993199,9889.0,1858.0,477.0,15665.666434,6.635854,42030.0,Education,Mobile,CA
...,...,...,...,...,...,...,...,...,...,...,...
110766,vid_2874,2024-07-16 10:50:40.993199,9919.0,1715.0,160.0,38731.665889,6.861374,31746.0,Music,Desktop,IN
110767,vid_3305,2025-03-02 10:50:40.993199,9817.0,776.0,315.0,41277.095579,23.864485,148767.0,Tech,Tablet,DE
110768,vid_4244,2025-05-24 10:50:40.993199,9948.0,1706.0,457.0,47161.520750,11.480903,918781.0,Lifestyle,Mobile,CA
110769,vid_2896,2024-08-01 10:50:40.993199,9991.0,1932.0,123.0,42551.046042,9.751237,648616.0,Entertainment,Mobile,CA
110770,vid_120,NaN,NaN,1104.0,274.0,37559.191594,NaN,NaN,NaN,NaN,NaN

In [12]:
y

0         203.178237
1         140.880508
2         360.134008
3         224.638261
4         165.514388
             ...
110766    266.509995
110767    264.504170
110768    311.353905
110769    287.985470
110770           NaN
Name: ad_revenue_usd, Length: 110771, dtype: float64

In [13]:
df['date']=pd.to_datetime(df['date'])

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 108814 entries, 0 to 110770
Data columns (total 17 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   video_id              108814 non-null  object
 1   date                  108813 non-null  datetime64[ns]
 2   views                 108813 non-null  float64
 3   likes                 108814 non-null  float64
 4   comments              108814 non-null  float64
 5   watch_time_minutes    108814 non-null  float64
 6   video_length_minutes  108813 non-null  float64
 7   subscribers           108813 non-null  float64
 8   category              108813 non-null  object
 9   device                108813 non-null  object
 10  country               108813 non-null  object
 11  ad_revenue_usd        108813 non-null  float64
 12  engagement_rate       108813 non-null  float64
 13  year                  108813 non-null  float64
 14  month                 108813 non-null  float64
 15  day_of_week           108813 non-null  float64
 16  hour                  108813 non-null  float64
dtypes: datetime64[ns](1), float64(12), object(4)
memory usage: 14.9+ MB

In [37]:
df.duplicated().sum()

np.int64(0)

In [38]:
df.drop_duplicates(inplace=True)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 108814 entries, 0 to 110770
Data columns (total 17 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   video_id              108814 non-null  object
 1   date                  108813 non-null  datetime64[ns]
 2   views                 108813 non-null  float64
 3   likes                 108814 non-null  float64
 4   comments              108814 non-null  float64
 5   watch_time_minutes    108814 non-null  float64
 6   video_length_minutes  108813 non-null  float64
 7   subscribers           108813 non-null  float64
 8   category              108813 non-null  object
 9   device                108813 non-null  object
 10  country               108813 non-null  object
 11  ad_revenue_usd        108813 non-null  float64
 12  engagement_rate       108813 non-null  float64
 13  year                  108813 non-null  float64
 14  month                 108813 non-null  float64
 15  day_of_week           108813 non-null  float64
 16  hour                  108813 non-null  float64
dtypes: datetime64[ns](1), float64(12), object(4)
memory usage: 14.9+ MB

In [40]:
print(df.isnull().sum())

video_id                0
date                    1
views                   1
likes                   0
comments                0
watch_time_minutes      0
video_length_minutes    1
subscribers             1
category                1
device                  1
country                 1
ad_revenue_usd          1
engagement_rate         1
year                    1
month                   1
day_of_week             1
hour                    1
dtype: int64

In [42]:
df = df.dropna()

In [97]:
print(df.isnull().sum())

video_id              0
date                  0
views                 0
likes                 0
comments              0
watch_time_minutes    0
subscribers           0
category              0
device                0
country               0
ad_revenue_usd        0
engagement_rate       0
day_of_week           0
hour                  0
dtype: int64

In [17]:
df['engagement_rate'] = (df['likes'] + df['comments']) / df['views']
df.head()

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country,ad_revenue_usd,engagement_rate
0,vid_3092,2024-09-24 10:50:40.993199,9936.0,1221.0,320.0,26497.214184,2.862137,228086.0,Entertainment,TV,IN,203.178237,0.155093
1,vid_3459,2024-09-22 10:50:40.993199,10017.0,642.0,346.0,15209.747445,23.738069,736015.0,Gaming,Tablet,CA,140.880508,0.098632
2,vid_4784,2024-11-21 10:50:40.993199,10097.0,1979.0,187.0,57332.658498,26.200634,240534.0,Education,TV,CA,360.134008,0.214519
3,vid_4078,2025-01-28 10:50:40.993199,10034.0,1191.0,242.0,31334.517771,11.770340,434482.0,Entertainment,Mobile,UK,224.638261,0.142814
4,vid_3522,2025-04-28 10:50:40.993199,9889.0,1858.0,477.0,15665.666434,6.635854,42030.0,Education,Mobile,CA,165.514388,0.236121

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 108814 entries, 0 to 110770
Data columns (total 13 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   video_id              108814 non-null  object
 1   date                  108813 non-null  datetime64[ns]
 2   views                 108813 non-null  float64
 3   likes                 108814 non-null  float64
 4   comments              108814 non-null  float64
 5   watch_time_minutes    108814 non-null  float64
 6   video_length_minutes  108813 non-null  float64
 7   subscribers           108813 non-null  float64
 8   category              108813 non-null  object
 9   device                108813 non-null  object
 10  country               108813 non-null  object
 11  ad_revenue_usd        108813 non-null  float64
 12  engagement_rate       108813 non-null  float64
dtypes: datetime64[ns](1), float64(8), object(4)
memory usage: 11.6+ MB

In [19]:
cat_col=df.select_dtypes(include=['object','category']).columns
print(cat_col)

Index(['video_id', 'category', 'device', 'country'], dtype='object')

In [20]:
df['category'].value_counts()

category
Education        18259
Tech             18182
Gaming           18174
Music            18167
Entertainment    18060
Lifestyle        17971
Name: count, dtype: int64

In [21]:
df['device'].value_counts()

device
TV         27304
Tablet     27191
Mobile     27170
Desktop    27148
Name: count, dtype: int64

In [75]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day_of_week'] = df['date'].dt.dayofweek
df['hour'] = df['date'].dt.hour
df.head()

,video_id,date,views,likes,comments,watch_time_minutes,video_length_minutes,subscribers,category,device,country,ad_revenue_usd,engagement_rate,year,month,day_of_week,hour
0,vid_3092,2024-09-24 10:50:40.993199,9936.0,1221.0,320.0,26497.214184,2.862137,228086.0,Entertainment,TV,IN,203.178237,0.155093,2024,9,1,10
1,vid_3459,2024-09-22 10:50:40.993199,10017.0,642.0,346.0,15209.747445,23.738069,736015.0,Gaming,Tablet,CA,140.880508,0.098632,2024,9,6,10
2,vid_4784,2024-11-21 10:50:40.993199,10097.0,1979.0,187.0,57332.658498,26.200634,240534.0,Education,TV,CA,360.134008,0.214519,2024,11,3,10
3,vid_4078,2025-01-28 10:50:40.993199,10034.0,1191.0,242.0,31334.517771,11.770340,434482.0,Entertainment,Mobile,UK,224.638261,0.142814,2025,1,1,10
4,vid_3522,2025-04-28 10:50:40.993199,9889.0,1858.0,477.0,15665.666434,6.635854,42030.0,Education,Mobile,CA,165.514388,0.236121,2025,4,0,10

In [ ]:
df.drop(columns=['video_length_minutes' ,'month','year'],axis=1,inplace=True)

In [99]:
df.drop(columns=['video_id'],axis=1,inplace=True)

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 108813 entries, 0 to 110769
Data columns (total 13 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   date                108813 non-null  datetime64[ns]
 1   views               108813 non-null  float64
 2   likes               108813 non-null  float64
 3   comments            108813 non-null  float64
 4   watch_time_minutes  108813 non-null  float64
 5   subscribers         108813 non-null  float64
 6   category            108813 non-null  object
 7   device              108813 non-null  object
 8   country             108813 non-null  object
 9   ad_revenue_usd      108813 non-null  float64
 10  engagement_rate     108813 non-null  float64
 11  day_of_week         108813 non-null  int32
 12  hour                108813 non-null  int32
dtypes: datetime64[ns](1), float64(7), int32(2), object(3)
memory usage: 10.8+ MB

In [101]:
X

,video_id,date,views,likes,comments,watch_time_minutes,subscribers,category,device,country,engagement_rate,day_of_week,hour
0,vid_3092,2024-09-24 10:50:40.993199,9936.0,1221.0,320.0,26497.214184,228086.0,Entertainment,TV,IN,0.155093,1,10
1,vid_3459,2024-09-22 10:50:40.993199,10017.0,642.0,346.0,15209.747445,736015.0,Gaming,Tablet,CA,0.098632,6,10
2,vid_4784,2024-11-21 10:50:40.993199,10097.0,1979.0,187.0,57332.658498,240534.0,Education,TV,CA,0.214519,3,10
3,vid_4078,2025-01-28 10:50:40.993199,10034.0,1191.0,242.0,31334.517771,434482.0,Entertainment,Mobile,UK,0.142814,1,10
4,vid_3522,2025-04-28 10:50:40.993199,9889.0,1858.0,477.0,15665.666434,42030.0,Education,Mobile,CA,0.236121,0,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
110765,vid_4367,2024-07-11 10:50:40.993199,10065.0,1331.0,418.0,49925.416738,159924.0,Tech,Mobile,UK,0.173770,3,10
110766,vid_2874,2024-07-16 10:50:40.993199,9919.0,1715.0,160.0,38731.665889,31746.0,Music,Desktop,IN,0.189031,1,10
110767,vid_3305,2025-03-02 10:50:40.993199,9817.0,776.0,315.0,41277.095579,148767.0,Tech,Tablet,DE,0.111134,6,10
110768,vid_4244,2025-05-24 10:50:40.993199,9948.0,1706.0,457.0,47161.520750,918781.0,Lifestyle,Mobile,CA,0.217431,5,10
110769,vid_2896,2024-08-01 10:50:40.993199,9991.0,1932.0,123.0,42551.046042,648616.0,Entertainment,Mobile,CA,0.205685,3,10

In [105]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 108813 entries, 0 to 110769
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   date                108813 non-null  datetime64[ns]
 1   views               108813 non-null  float64
 2   likes               108813 non-null  float64
 3   comments            108813 non-null  float64
 4   watch_time_minutes  108813 non-null  float64
 5   subscribers         108813 non-null  float64
 6   category            108813 non-null  object
 7   device              108813 non-null  object
 8   country             108813 non-null  object
 9   engagement_rate     108813 non-null  float64
 10  day_of_week         108813 non-null  int32
 11  hour                108813 non-null  int32
dtypes: datetime64[ns](1), float64(6), int32(2), object(3)
memory usage: 10.0+ MB

In [106]:
# 1. Encode categorical features
encoder_onehot = OneHotEncoder(drop='first', sparse_output=False) # drop='first' to avoid dummy variable trap / # or sparse=True for large data
encoder_onehot = encoder_onehot.fit_transform(df[['category', 'device', 'country']]) # fit and transform categorical columns
print(encoder_onehot)

[[1. 0. 0. ... 1. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]

In [104]:
X=df.drop('ad_revenue_usd',axis=1) # independent variable / Features / X
Y=df['ad_revenue_usd'] # dependent variable / Target/Label / y

In [107]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42)

In [108]:
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler, OneHotEncoder

# Define columns based on scaling strategy
minmax_cols = ["watch_time_minutes"]        # wide range → MinMaxScaler
robust_cols = ["subscribers"]               # heavy outliers → RobustScaler
standard_cols = ["likes", "comments"]       # normal-like → StandardScaler
# engagement_rate already small (0–0.25), no scaling needed

# Initialize scalers
scaler_minmax = MinMaxScaler()
scaler_robust = RobustScaler()
scaler_standard = StandardScaler()

# Work on copies (avoid modifying original data)
X_train_scaled = X_train.copy()
X_test_scaled = X_test.copy()

# Apply RobustScaler
X_train_scaled[robust_cols] = scaler_robust.fit_transform(X_train[robust_cols])
X_test_scaled[robust_cols] = scaler_robust.transform(X_test[robust_cols])

# Apply MinMaxScaler
X_train_scaled[minmax_cols] = scaler_minmax.fit_transform(X_train[minmax_cols])
X_test_scaled[minmax_cols] = scaler_minmax.transform(X_test[minmax_cols])

# Apply StandardScaler
X_train_scaled[standard_cols] = scaler_standard.fit_transform(X_train[standard_cols])
X_test_scaled[standard_cols] = scaler_standard.transform(X_test[standard_cols])

# Identify remaining columns
numeric_cols = X.select_dtypes(include=['float64', 'int64']).columns.difference(
    robust_cols + minmax_cols + standard_cols
)
categorical_cols = X.select_dtypes(include=['object']).columns

In [109]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num_standard', StandardScaler(), numeric_cols),
        ('num_robust', RobustScaler(), robust_cols),
        ('num_minmax', MinMaxScaler(), minmax_cols),
        ('cat', OneHotEncoder(drop='first', handle_unknown='ignore'), categorical_cols)
    ]
)

Linear Regression

In [110]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

pipe_lr = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', LinearRegression())
])

pipe_lr.fit(X_train, y_train)

y_train_pred_lr = pipe_lr.predict(X_train)
y_test_pred_lr = pipe_lr.predict(X_test)

print('LinearRegression Evaluation')
print('Train r2_score:',r2_score(y_train,y_train_pred_lr))
print('Test r2_score:',r2_score(y_test,y_test_pred_lr))
print('***'*10)
print('Train mean_squared_error:',mean_squared_error(y_train,y_train_pred_lr))
print('Test mean_squared_error:',mean_squared_error(y_test,y_test_pred_lr))
print('***'*10)
print('Train mean_absolute_error:',mean_absolute_error(y_train,y_train_pred_lr))
print('Test mean_absolute_error:',mean_absolute_error(y_test,y_test_pred_lr))
print('***'*10)
#7s

LinearRegression Evaluation
Train r2_score: 0.9494347321701384
Test r2_score: 0.9514276906728628
******************************
Train mean_squared_error: 193.58323633164915
Test mean_squared_error: 186.69237586808353
******************************
Train mean_absolute_error: 3.2676695843133965
Test mean_absolute_error: 3.1547721970225013
******************************

Polynomial

In [111]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.feature_selection import SelectKBest, f_regression

pipe_lr_poly = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('poly', PolynomialFeatures(degree=2, include_bias=False)),
    ('select', SelectKBest(score_func=f_regression, k=100)),  # keep best 100 features
    ('model', LinearRegression())
])

pipe_lr_poly.fit(X_train, y_train)

y_train_pred_poly = pipe_lr_poly.predict(X_train)
y_test_pred_poly = pipe_lr_poly.predict(X_test)

print('PolynomialFeatures Evaluation')
print('Train r2_score:',r2_score(y_train,y_train_pred_poly))
print('Test r2_score:',r2_score(y_test,y_test_pred_poly))
print('***'*10)
print('Train mean_squared_error:',mean_squared_error(y_train,y_train_pred_poly))
print('Test mean_squared_error:',mean_squared_error(y_test,y_test_pred_poly))
print('***'*10)
print('Train mean_absolute_error:',mean_absolute_error(y_train,y_train_pred_poly))
print('Test mean_absolute_error:',mean_absolute_error(y_test,y_test_pred_poly))
print('***'*10)
#5s

PolynomialFeatures Evaluation
Train r2_score: 0.9494868569619008
Test r2_score: 0.9513929059944445
******************************
Train mean_squared_error: 193.38368263964787
Test mean_squared_error: 186.82607414901113
******************************
Train mean_absolute_error: 3.464501853175089
Test mean_absolute_error: 3.3560153900689698
******************************

Lasso Regression

In [112]:
pipe_lasso = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', Lasso(alpha=0.1, random_state=42))
])

pipe_lasso.fit(X_train, y_train)

y_train_pred_lasso = pipe_lasso.predict(X_train)
y_test_pred_lasso = pipe_lasso.predict(X_test)

print("Lasso Regression Evaluation")
print('Train r2_score:', r2_score(y_train, y_train_pred_lasso))
print('Test r2_score:', r2_score(y_test, y_test_pred_lasso))
print('***'*10)
print('Train MSE:', mean_squared_error(y_train, y_train_pred_lasso))
print('Test MSE:', mean_squared_error(y_test, y_test_pred_lasso))
print('***'*10)
print('Train MAE:', mean_absolute_error(y_train, y_train_pred_lasso))
print('Test MAE:', mean_absolute_error(y_test, y_test_pred_lasso))
print('***'*10)
#4s

Lasso Regression Evaluation
Train r2_score: 0.9493876263101212
Test r2_score: 0.9513986414169774
******************************
Train MSE: 193.76357562823887
Test MSE: 186.80402949694277
******************************
Train MAE: 3.434730005947714
Test MAE: 3.321747201601709
******************************

Ridge Regression

In [113]:
pipe_ridge = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', Ridge(alpha=1.0, random_state=42))
])

pipe_ridge.fit(X_train, y_train)

y_train_pred_ridge = pipe_ridge.predict(X_train)
y_test_pred_ridge = pipe_ridge.predict(X_test)

print("Ridge Regression Evaluation")
print('Train r2_score:', r2_score(y_train, y_train_pred_ridge))
print('Test r2_score:', r2_score(y_test, y_test_pred_ridge))
print('***'*10)
print('Train MSE:', mean_squared_error(y_train, y_train_pred_ridge))
print('Test MSE:', mean_squared_error(y_test, y_test_pred_ridge))
print('***'*10)
print('Train MAE:', mean_absolute_error(y_train, y_train_pred_ridge))
print('Test MAE:', mean_absolute_error(y_test, y_test_pred_ridge))
print('***'*10)
#4s

Ridge Regression Evaluation
Train r2_score: 0.949434702089045
Test r2_score: 0.9514276612280832
******************************
Train MSE: 193.58335149361042
Test MSE: 186.69248904194643
******************************
Train MAE: 3.267665182396854
Test MAE: 3.1547644197750317
******************************

Elastic Net

In [114]:
from sklearn.linear_model import ElasticNet

pipe_elastic = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', ElasticNet(alpha=0.1, l1_ratio=0.5, random_state=42))
])

pipe_elastic.fit(X_train, y_train)

y_train_pred_elastic = pipe_elastic.predict(X_train)
y_test_pred_elastic = pipe_elastic.predict(X_test)

print("Elastic Net Regression Evaluation")
print('Train r2_score:', r2_score(y_train, y_train_pred_elastic))
print('Test r2_score:', r2_score(y_test, y_test_pred_elastic))
print('***'*10)
print('Train MSE:', mean_squared_error(y_train, y_train_pred_elastic))
print('Test MSE:', mean_squared_error(y_test, y_test_pred_elastic))
print('***'*10)
print('Train MAE:', mean_absolute_error(y_train, y_train_pred_elastic))
print('Test MAE:', mean_absolute_error(y_test, y_test_pred_elastic))
print('***'*10)
#4s

Elastic Net Regression Evaluation
Train r2_score: 0.7945088901325138
Test r2_score: 0.7962364740950656
******************************
Train MSE: 786.6987715634797
Test MSE: 783.1848494219439
******************************
Train MAE: 23.260354316677624
Test MAE: 23.266971070872437
******************************

RF Regression

In [115]:
pipe_rf = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', RandomForestRegressor(n_estimators=200,max_depth=10,max_features='sqrt', random_state=42))
])

pipe_rf.fit(X_train, y_train)

y_train_pred_rf = pipe_rf.predict(X_train)
y_test_pred_rf = pipe_rf.predict(X_test)

print('RandomForestRegressor Evaluation')
print('Train r2_score:',r2_score(y_train,y_train_pred_rf))
print('Test r2_score:',r2_score(y_test,y_test_pred_rf))
print('***'*10)
print('Train mean_squared_error:',mean_squared_error(y_train,y_train_pred_rf))
print('Test mean_squared_error:',mean_squared_error(y_test,y_test_pred_rf))
print('***'*10)
print('Train mean_absolute_error:',mean_absolute_error(y_train,y_train_pred_rf))
print('Test mean_absolute_error:',mean_absolute_error(y_test,y_test_pred_rf))
print('***'*10)
#13s

RandomForestRegressor Evaluation
Train r2_score: 0.9177975125127871
Test r2_score: 0.9145069655969946
******************************
Train mean_squared_error: 314.70264561496185
Test mean_squared_error: 328.6007590327104
******************************
Train mean_absolute_error: 11.365132947788629
Test mean_absolute_error: 11.663065910053431
******************************

Gradient Boosting Regression

In [116]:
from sklearn.ensemble import GradientBoostingRegressor

pipe_gb = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', GradientBoostingRegressor(n_estimators=100, random_state=42))
])

pipe_gb.fit(X_train, y_train)

y_train_pred_gb = pipe_gb.predict(X_train)
y_test_pred_gb = pipe_gb.predict(X_test)

print('GradientBoostingRegressor Evaluation')
print('Train r2_score:',r2_score(y_train,y_train_pred_gb))
print('Test r2_score:',r2_score(y_test,y_test_pred_gb))
print('***'*10)
print('Train mean_squared_error:',mean_squared_error(y_train,y_train_pred_gb))
print('Test mean_squared_error:',mean_squared_error(y_test,y_test_pred_gb))
print('***'*10)
print('Train mean_absolute_error:',mean_absolute_error(y_train,y_train_pred_gb))
print('Test mean_absolute_error:',mean_absolute_error(y_test,y_test_pred_gb))
print('***'*10)
#36s

GradientBoostingRegressor Evaluation
Train r2_score: 0.9497771581271359
Test r2_score: 0.9511676702604188
******************************
Train mean_squared_error: 192.27229845265703
Test mean_squared_error: 187.69178951025617
******************************
Train mean_absolute_error: 3.746529245079486
Test mean_absolute_error: 3.677607524868304
******************************

In [117]:
import pickle
pickle.dump(pipe_lr, open("lr.pkl", "wb"))
pickle.dump(pipe_lr_poly, open("lr_poly.pkl", "wb"))
pickle.dump(pipe_lasso, open("lasso.pkl", "wb"))
pickle.dump(pipe_ridge, open("ridge.pkl", "wb"))
pickle.dump(pipe_elastic, open("elastic.pkl", "wb"))
pickle.dump(pipe_rf, open("rf.pkl", "wb"))
pickle.dump(pipe_gb, open("gb.pkl", "wb"))

In [68]:
import pickle
pickle.dump(pipe_rf, open("rf.pkl", "wb"))
pickle.dump(pipe_gb, open("gb.pkl", "wb"))

In [118]:
import pandas as pd

In [119]:
# Collect metrics in a dictionary
results = {
    "Model": [],
    "Train R2": [],
    "Test R2": [],
    "Train MSE": [],
    "Test MSE": [],
    "Train MAE": [],
    "Test MAE": []
}

In [120]:
# Helper function to append results
def add_results(model_name, y_train, y_train_pred, y_test, y_test_pred):
    results["Model"].append(model_name)
    results["Train R2"].append(r2_score(y_train, y_train_pred))
    results["Test R2"].append(r2_score(y_test, y_test_pred))
    results["Train MSE"].append(mean_squared_error(y_train, y_train_pred))
    results["Test MSE"].append(mean_squared_error(y_test, y_test_pred))
    results["Train MAE"].append(mean_absolute_error(y_train, y_train_pred))
    results["Test MAE"].append(mean_absolute_error(y_test, y_test_pred))

# Add each model’s results
add_results("LinearRegression", y_train, y_train_pred_lr, y_test, y_test_pred_lr)
add_results("Polynomial Regression", y_train, y_train_pred_poly, y_test, y_test_pred_poly)
add_results("Lasso", y_train, y_train_pred_lasso, y_test, y_test_pred_lasso)
add_results("Ridge", y_train, y_train_pred_ridge, y_test, y_test_pred_ridge)
add_results("ElasticNet", y_train, y_train_pred_elastic, y_test, y_test_pred_elastic)
add_results("RandomForest", y_train, y_train_pred_rf, y_test, y_test_pred_rf)
add_results("GradientBoosting", y_train, y_train_pred_gb, y_test, y_test_pred_gb)

# Convert to DataFrame
results_df = pd.DataFrame(results)

# Sort by best Test R2 (higher is better)
results_df = results_df.sort_values(by="Test R2", ascending=False).reset_index(drop=True)

results_df

,Model,Train R2,Test R2,Train MSE,Test MSE,Train MAE,Test MAE
0,LinearRegression,0.949435,0.951428,193.583236,186.692376,3.267670,3.154772
1,Ridge,0.949435,0.951428,193.583351,186.692489,3.267665,3.154764
2,Lasso,0.949388,0.951399,193.763576,186.804029,3.434730,3.321747
3,Polynomial Regression,0.949487,0.951393,193.383683,186.826074,3.464502,3.356015
4,GradientBoosting,0.949777,0.951168,192.272298,187.691790,3.746529,3.677608
5,RandomForest,0.917798,0.914507,314.702646,328.600759,11.365133,11.663066
6,ElasticNet,0.794509,0.796236,786.698772,783.184849,23.260354,23.266971